baseURL = 'https://belfryupkeep.cccbr.org.uk'
languageCode = 'en-us'
title = 'Belfry Upkeep'
theme = 'hugo-book'
sidebar_search_disable = false
publishDir = "docs/"

[params]
  BookLogo = 'favicon.png'
